### ISSUE TITLE
Classify the existing platforms into something more intuitive.

### ISSUE THREAD

**Issue by DasherPack** [TheodoreHua/ToR-Platform-Chart#28]
We need to classify the table into some categories to make looking for what you want easier.

**Comment by TheodoreHua** [comment]
What would be some good subcategories to sort the table into? Social Media and Other? I can't really think of any sorting that would actually be meaningful (e.g. Social Media and other would result in 2 subcategories and there would only be 3 entries in the other category).

**Comment by MollyMaclachlan** [comment]
Video-sharing; forums; whatever the hell twitter is?

Could be a start.

**Comment by TheodoreHua** [comment]
Good idea, thanks murdo

**Comment by TheodoreHua** [comment]
How does the current sorting in the [reformat branch](https://github.com/TheodoreHua/ToR-Platform-Chart/tree/reformat) look?
